choco install viber
choco install airexplorer
choco install firefox
choco install discord
choco install bitwarden
choco install vscode
choco install fiddler
choco install figma
choco install googlechrome
choco install mkvtoolnix
choco install winquicklook
choco install sharex
choco install slack
choco install steam
choco install treesizefree
choco install zoom
choco install 7zip
