choco install firefox
choco install discord
choco install bitwarden
choco install vscode
choco install figma
choco install fiddler
choco install googlechrome
choco install treesizefree
choco install slack
choco install steam
choco install zoom
choco install 7zip
